_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 55
                - 105
            "2":
                - 55
                - 105
            "3":
                - 13
                - 16
                - 23
                - 24
                - 55
            "4": 3.12.7
            "5": 0.19.5
            "8":
                - 1
                - 5
            "12": 0.19.5
            "13": darwin-arm64
checkpoint_interval:
    value: 10
data_path:
    value: CohleM/olympiad_small
ddp_size:
    value: 1
lr:
    value: 1e-06
max_eps:
    value: 0.2
min_eps:
    value: 0.2
model_name:
    value: Qwen/Qwen2.5-0.5B-Instruct
offload_model:
    value: true
per_rollout_size:
    value: 3
responses_per_prompt:
    value: 2
resume_steps:
    value: 0
temperature:
    value: 1
tp_size:
    value: 2
train_batch_size:
    value: 64
updates_per_rollout:
    value: 3
